version: '3'
services:
  bosch2mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bosch2mqtt
    image: bosch2mqtt:0.3
    stdin_open: true
    network_mode: host
    tty: true
    environment:
      - MBLAN_ACCESS_KEY=${MBLAN_ACCESS_KEY}
      - MBLAN_PASSWORD=${MBLAN_PASSWORD}
      - MBLAN_IP=${MBLAN_IP}
      - MBLAN_SLEEP=${MBLAN_SLEEP}
      - MQTT_IP=${MQTT_IP}
      - MQTT_PORT=${MQTT_PORT}
    restart: "unless-stopped"
